// ...existing code...

const swiper = new Swiper('.swiper-container', {
    // ...existing configuration...
    autoplay: {
        delay: 3000, // Delay between slides in milliseconds
        disableOnInteraction: false, // Autoplay will not be disabled after user interactions
    },
    // ...existing configuration...
});

// ...existing code...